# Databricks Apps configuration file
# This file defines the application specification for Databricks Apps deployment

# Command to launch the application
command:
  - python
  - app.py

# Environment variables
env:
  # Python configuration
  - name: PYTHONPATH
    value: "./workspace"
  
  - name: PYTHONUNBUFFERED
    value: "1"
  
  # Workspace directory (Databricks Apps provides this)
  - name: WORKSPACE_DIR
    valueFrom: volume
  
  # Port (Databricks Apps provides this via PORT environment variable)
  - name: PORT
    value: "8000"
  
  # Host binding
  - name: HOST
    value: "0.0.0.0"
