# Databricks Apps configuration file
# This file defines the application specification for Databricks Apps deployment

# Command to launch the application
command:
  - python
  - app.py

# Environment variables
env:
  # Python configuration
  - name: PYTHONPATH
    value: "./workspace"
  
  - name: PYTHONUNBUFFERED
    value: "1"
  
  # Workspace directory (Databricks Apps provides this)
  - name: WORKSPACE_DIR
    valueFrom: volume
  
  # Port (Databricks Apps provides this via PORT environment variable)
  - name: PORT
    value: "8000"
  
  # Host binding
  - name: HOST
    value: "0.0.0.0"
  
  # OpenAI API Key from secret
  - name: OPENAI_API_KEY
    valueFrom: OPENAI_API_KEY

# Database configuration for PostgreSQL/Lakebase
# Use DB_ENV environment variable to switch between 'local' and 'databricks'
# Default is 'databricks' if not specified

# Databricks Postgres configuration
database_databricks:
  host: "instance-3af3a681-723d-4026-b9d0-2a29fc754893.database.cloud.databricks.com"
  port: 5432
  database: "databricks_postgres"
  user: "dev_user"
  password: "test12345"  # Consider using a secret in production

# Local Postgres configuration (for development)
database_local:
  host: "localhost"
  port: 5432
  database: "antongorshkov"  # Change to your local database name if different
  user: "antongorshkov"      # Change to your local PostgreSQL user if different
  password: ""          # Set your local PostgreSQL password if required
